# Generated by Django 2.2.9 on 2020-04-22 14:29

from django.db import migrations, models
import django.db.models.deletion
import recruting.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200313_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.Category'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'manager'), (3, 'employee')], null=True, validators=[recruting.main.models.validate_role]),
        ),
    ]
