# Generated by Django 2.2.9 on 2020-04-19 15:37

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_task_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments', validators=[utils.validators.validate_file_size]),
        ),
    ]
